#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

#app_widget:
#    path: /widget/pouet
#    defaults: { _controller: 'App\Controller\WidgetController::pouet' }
